# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # deps
  - package-ecosystem: npm
    reviewers:
    - '@MapColonies/infra'
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    labels:
      - 'infra'
    directory: /
    commit-message:
      prefix: "deps"
    groups:
      map-colonies:
        patterns:
          - "@map-colonies/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      patch:
        update-types:
          - patch
          - minor
  # dev-deps
  - package-ecosystem: npm
    reviewers:
    - '@MapColonies/infra'
    schedule:
      interval: weekly
    allow:
      - dependency-type: development
    labels:
      - 'infra'
    directory: /
    commit-message:
      prefix: "deps"
    groups:
      map-colonies:
        patterns:
          - "@map-colonies/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      types:
        patterns:
          - "@types/*"
      dev-patch:
        update-types:
          - patch
          - minor
    
  # github deps
  - package-ecosystem: github-actions
    schedule: 
      interval: weekly
    labels:
      - 'infra'
    commit-message:
      prefix: "ci"
    directory: "/"
